import type { Routine } from '@/lib/types';

export const friendRoutines: Routine[] = [
  // ─────────────────────────────────────────────
  // FULL-BODY KETTLEBELL (16–20)
  // ─────────────────────────────────────────────
  {
    id: 'kb-foundation-builder',
    number: 16,
    name: 'KB Foundation Builder',
    durationMin: 40,
    group: 'full_body',
    intensity: 'medium',
    whenToDo:
      'Default KB session. 2x/week if KB is your only lift, 1x/week if you also gym. The bread-and-butter day.',
    whyItWorks:
      'Hits the four KB pillars — hinge (swing), squat (goblet), press, row — at moderate volume. Builds the patterns before you load them heavy.',
    exercises: [
      {
        name: 'Warmup: KB halos',
        prescription: '10 each direction',
        type: 'reps',
        reps: 10,
        segments: ['Clockwise', 'Counter-clockwise'],
      },
      {
        name: 'Warmup: goblet squat (light)',
        prescription: '2 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2'],
      },
      {
        name: 'Two-hand KB swing',
        prescription: '5 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Goblet squat',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Single-arm KB clean & press',
        prescription: '4 sets × 6/side',
        type: 'reps',
        reps: 6,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Single-arm KB row',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'KB front-rack carry',
        prescription: '3 sets × 40s',
        type: 'time',
        durationSec: 40,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Cooldown: deep squat hold',
        prescription: '60s',
        type: 'time',
        durationSec: 60,
      },
    ],
  },
  {
    id: 'heavy-double-kb-strength',
    number: 17,
    name: 'Heavy Double KB Strength',
    durationMin: 50,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Strength day. 1x/week, with at least 48h before next hard session. Use heavier of the pair.',
    whyItWorks:
      'Double KB front squat + double press are the two highest-bang KB strength lifts. Low reps, longer rest = real strength adaptation, not just sweat.',
    exercises: [
      {
        name: 'Warmup: 2-hand swing',
        prescription: '3 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Warmup: goblet squat',
        prescription: '2 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2'],
      },
      {
        name: 'Double KB front squat',
        prescription: '5 sets × 5 (rest 2 min)',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Double KB military press',
        prescription: '5 sets × 5 (rest 2 min)',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Double KB bent-over row',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Single-arm KB swing',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Turkish get-up',
        prescription: '3 sets × 2/side',
        type: 'reps',
        reps: 2,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
    ],
  },
  {
    id: 'kb-emom-conditioning',
    number: 18,
    name: 'KB EMOM Conditioning',
    durationMin: 30,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Conditioning day. Use a moderate KB — heavy enough to challenge, light enough that form holds. Skip if heart rate is already elevated from a prior session.',
    whyItWorks:
      '20-min EMOM is the cleanest dose for KB conditioning — you’re forced to pace, and the rotating movements keep no single muscle from blowing up too early.',
    exercises: [
      {
        name: 'Warmup: halos + goblet squats',
        prescription: '2 min flow',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Warmup: 2-hand swing',
        prescription: '2 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2'],
      },
      {
        name: 'EMOM Min 1 — KB swings × 15',
        prescription: '60s window',
        type: 'time',
        durationSec: 60,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4', 'Round 5'],
      },
      {
        name: 'EMOM Min 2 — Goblet squats × 10',
        prescription: '60s window',
        type: 'time',
        durationSec: 60,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4', 'Round 5'],
      },
      {
        name: 'EMOM Min 3 — Push-press × 6/side',
        prescription: '60s window',
        type: 'time',
        durationSec: 60,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4', 'Round 5'],
      },
      {
        name: 'EMOM Min 4 — KB rows × 8/side',
        prescription: '60s window',
        type: 'time',
        durationSec: 60,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4', 'Round 5'],
      },
      {
        name: 'Cooldown walk + stretches',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
    ],
  },
  {
    id: 'kb-getup-carry-day',
    number: 19,
    name: 'KB Get-Up & Carry Day',
    durationMin: 40,
    group: 'full_body',
    intensity: 'medium',
    whenToDo:
      'The "skill" day — between heavy sessions. Lower-back-friendly, builds shoulder stability and grip without crushing the CNS.',
    whyItWorks:
      'Get-ups + asymmetric carries train every stabilizer the swing/squat/press miss. People who skip this day plateau in their main lifts within months.',
    exercises: [
      {
        name: 'Warmup: halos + arm bars',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Turkish get-up',
        prescription: '5 sets × 2/side',
        type: 'reps',
        reps: 2,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
          'Set 5 — Right',
          'Set 5 — Left',
        ],
      },
      {
        name: 'Single-arm KB press',
        prescription: '4 sets × 6/side',
        type: 'reps',
        reps: 6,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'KB suitcase carry',
        prescription: '4 sets × 40s/side',
        type: 'time',
        durationSec: 40,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'KB overhead carry',
        prescription: '4 sets × 30s/side',
        type: 'time',
        durationSec: 30,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'KB windmill (light)',
        prescription: '3 sets × 5/side',
        type: 'reps',
        reps: 5,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Goblet squat',
        prescription: '3 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'kb-swing-conditioning',
    number: 20,
    name: 'KB Swing Conditioning',
    durationMin: 30,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Pure posterior chain + cardio session. Don’t do the day before deadlifts or heavy lower body.',
    whyItWorks:
      'Heavy swings = best hip-hinge cardio there is. EMOM swings build glute/ham/grip endurance simultaneously while parking heart rate around threshold.',
    exercises: [
      {
        name: 'Warmup: KB deadlifts + halos',
        prescription: '3 min flow',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Warmup: 2-hand swing (light)',
        prescription: '2 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2'],
      },
      {
        name: '2-hand swing EMOM × 10 reps',
        prescription: '10 rounds × 10 swings',
        type: 'time',
        durationSec: 60,
        segments: [
          'Round 1',
          'Round 2',
          'Round 3',
          'Round 4',
          'Round 5',
          'Round 6',
          'Round 7',
          'Round 8',
          'Round 9',
          'Round 10',
        ],
      },
      {
        name: 'Single-arm KB swing',
        prescription: '5 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
          'Set 5 — Right',
          'Set 5 — Left',
        ],
      },
      {
        name: 'Goblet squat',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Hollow hold',
        prescription: '3 sets × 30s',
        type: 'time',
        durationSec: 30,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Cooldown: legs-up-the-wall',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
    ],
  },

  // ─────────────────────────────────────────────
  // KETTLEBELL + BODYWEIGHT (21–25)
  // ─────────────────────────────────────────────
  {
    id: 'kb-bw-strength-mix',
    number: 21,
    name: 'KB + BW Strength Mix',
    durationMin: 45,
    group: 'full_body',
    intensity: 'medium',
    whenToDo:
      'Default hybrid day. Pull-ups carry the upper-back work that KB alone misses — that’s the whole point of pairing them.',
    whyItWorks:
      "KB hammers the loaded patterns; bodyweight (especially pull-ups, push-ups) covers what KB can't. Together = balanced full-body without needing a gym.",
    exercises: [
      {
        name: 'Warmup: jump rope + halos',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Goblet squat',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Pull-up',
        prescription: '4 sets × 6',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'KB push-press',
        prescription: '4 sets × 8/side',
        type: 'reps',
        reps: 8,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Push-up',
        prescription: '4 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Single-arm KB row',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Bodyweight reverse lunge',
        prescription: '3 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'kb-bw-circuit',
    number: 22,
    name: 'KB + BW Circuit',
    durationMin: 35,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Conditioning circuit — 4 rounds, minimal rest between exercises (60–90s rest between rounds). Picks up where straight-set days leave off.',
    whyItWorks:
      'Continuous movement across full body keeps heart rate elevated while still working real strength patterns. The goblet/swing/row mix prevents grip from being the limiting factor.',
    exercises: [
      {
        name: 'Warmup: dynamic flow',
        prescription: '4 min',
        type: 'time',
        durationSec: 240,
      },
      {
        name: 'KB swing',
        prescription: '4 rounds × 15',
        type: 'reps',
        reps: 15,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4'],
      },
      {
        name: 'Push-up',
        prescription: '4 rounds × 12',
        type: 'reps',
        reps: 12,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4'],
      },
      {
        name: 'Goblet squat',
        prescription: '4 rounds × 10',
        type: 'reps',
        reps: 10,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4'],
      },
      {
        name: 'Pull-up (or inverted row)',
        prescription: '4 rounds × 6',
        type: 'reps',
        reps: 6,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4'],
      },
      {
        name: 'KB walking lunge',
        prescription: '4 rounds × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Round 1 — Right',
          'Round 1 — Left',
          'Round 2 — Right',
          'Round 2 — Left',
          'Round 3 — Right',
          'Round 3 — Left',
          'Round 4 — Right',
          'Round 4 — Left',
        ],
      },
      {
        name: 'Plank',
        prescription: '4 rounds × 30s',
        type: 'time',
        durationSec: 30,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4'],
      },
      {
        name: 'Cooldown',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
    ],
  },
  {
    id: 'kb-bw-amrap-density',
    number: 23,
    name: 'KB + BW AMRAP Density',
    durationMin: 25,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Short, brutal day. AMRAP format pushes pacing skills — score it, beat it next time. Don’t stack with another conditioning session same week.',
    whyItWorks:
      'Density work (more work in fixed time) is the most efficient way to bridge strength and conditioning. The clean & press anchors it as real loaded work, not just cardio.',
    exercises: [
      {
        name: 'Warmup: full-body flow',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: '15-min AMRAP — round structure',
        prescription:
          '5 KB clean & press/side, 10 burpees, 15 goblet squats. Score = total rounds + reps.',
        type: 'time',
        durationSec: 900,
      },
      {
        name: 'Cooldown walk',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Couch stretch',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
    ],
  },
  {
    id: 'kb-bw-core-carries',
    number: 24,
    name: 'KB + BW Core & Carries',
    durationMin: 35,
    group: 'full_body',
    intensity: 'medium',
    whenToDo:
      'Active accessory day between heavy sessions. Builds the trunk + grip foundation that carries every lift heavier.',
    whyItWorks:
      'Loaded carries are the most underused tool in fitness — they hit core, traps, grip, and conditioning in one shot. Pair with anti-extension/anti-rotation core and you fix what every desk worker is missing.',
    exercises: [
      {
        name: 'Warmup: dead bug + bird dog',
        prescription: '2 min flow',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'KB suitcase carry',
        prescription: '4 sets × 40s/side',
        type: 'time',
        durationSec: 40,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'KB overhead carry',
        prescription: '4 sets × 30s/side',
        type: 'time',
        durationSec: 30,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Push-up variations (decline / standard / diamond)',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: [
          'Set 1 — Decline',
          'Set 2 — Standard',
          'Set 3 — Diamond',
          'Set 4 — Standard',
        ],
      },
      {
        name: 'Hanging leg raise',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Hollow hold',
        prescription: '4 sets × 30s',
        type: 'time',
        durationSec: 30,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'KB Russian twist',
        prescription: '3 sets × 20',
        type: 'reps',
        reps: 20,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Side plank',
        prescription: '3 sets × 30s/side',
        type: 'time',
        durationSec: 30,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
    ],
  },
  {
    id: 'kb-bw-athletic-power',
    number: 25,
    name: 'KB + BW Athletic Power',
    durationMin: 35,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Once a week max. Explosive day — needs fresh legs and CNS. Skip if you slept badly or did anything heavy yesterday.',
    whyItWorks:
      'Jumps + KB swings + push-press = triple-extension and explosive output everywhere. This is what keeps you athletic instead of just strong.',
    exercises: [
      {
        name: 'Warmup: dynamic — leg swings, A-skips, jump rope',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'KB swing (heavy, explosive)',
        prescription: '5 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Box jump (or jump squat)',
        prescription: '5 sets × 6 (rest 90s)',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'KB push-press',
        prescription: '4 sets × 6/side',
        type: 'reps',
        reps: 6,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Burpee',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'KB walking lunge',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // GYM FULL BODY (26–30)
  // ─────────────────────────────────────────────
  {
    id: 'gym-compound-5x5',
    number: 26,
    name: 'Gym Compound 5×5',
    durationMin: 60,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'The strength anchor of the week. 1–2x/week max, with at least 2 days between. Add weight when you hit all 5×5 with clean form.',
    whyItWorks:
      'Squat, bench, row, RDL, pull-up — five lifts that cover the entire body. 5×5 is the highest-ROI rep scheme for intermediate strength gains. If only one gym day exists, this is it.',
    exercises: [
      {
        name: 'Warmup: bike or row',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'Warmup: dynamic mobility (CARs + leg swings)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Back squat',
        prescription: '5 sets × 5 (rest 2–3 min)',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Bench press',
        prescription: '5 sets × 5 (rest 2–3 min)',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Bent-over barbell row',
        prescription: '5 sets × 5',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Romanian deadlift',
        prescription: '3 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Pull-up (weighted if able)',
        prescription: '3 sets × AMRAP',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'gym-heavy-pull-push',
    number: 27,
    name: 'Gym Heavy Pull/Push',
    durationMin: 65,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Heavy day — pairs with the 5×5 day, do them at least 48h apart. Deadlift is the centerpiece, treat it like a real lift.',
    whyItWorks:
      'Deadlift + overhead press are the two lifts the 5×5 day misses. Together those two days cover the full strength matrix at low rep ranges where actual strength is built.',
    exercises: [
      {
        name: 'Warmup: bike + dynamic',
        prescription: '8 min',
        type: 'time',
        durationSec: 480,
      },
      {
        name: 'Deadlift',
        prescription: '5 sets × 3 (rest 3 min)',
        type: 'reps',
        reps: 3,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Standing overhead press',
        prescription: '5 sets × 5',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Pull-up (weighted)',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB bench press',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Barbell row',
        prescription: '4 sets × 6',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Farmer carry',
        prescription: '3 sets × 40s',
        type: 'time',
        durationSec: 40,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'gym-hypertrophy-full-body',
    number: 28,
    name: 'Gym Hypertrophy Full Body',
    durationMin: 60,
    group: 'full_body',
    intensity: 'medium',
    whenToDo:
      'Volume day. Slot between the two heavy days — moderate weight, higher reps, less CNS cost. This is where size shows up.',
    whyItWorks:
      'Heavy days build strength; this day builds the muscle. 8–12 rep range with controlled tempo on every major muscle group = the hypertrophy sweet spot.',
    exercises: [
      {
        name: 'Warmup: cardio + mobility',
        prescription: '8 min',
        type: 'time',
        durationSec: 480,
      },
      {
        name: 'Front squat (or goblet squat heavy)',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Romanian deadlift',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Incline DB press',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Lat pulldown',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Cable row',
        prescription: '4 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB bicep curl',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Triceps pushdown',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hanging leg raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'gym-athletic-conditioning',
    number: 29,
    name: 'Gym Athletic Conditioning',
    durationMin: 50,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Mixed-modal day. Power output + conditioning. Don’t do the day before heavy squat or deadlift — power cleans tax the same systems.',
    whyItWorks:
      'Power cleans + push press build explosive strength the slow lifts miss. Adding sled or rower at the end pushes capacity without grinding joints. The athletic counterbalance to grind days.',
    exercises: [
      {
        name: 'Warmup: dynamic + jump rope',
        prescription: '6 min',
        type: 'time',
        durationSec: 360,
      },
      {
        name: 'Power clean (or DB hang clean)',
        prescription: '5 sets × 3',
        type: 'reps',
        reps: 3,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Push press',
        prescription: '4 sets × 5',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Box jump',
        prescription: '4 sets × 5',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB row',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Sled push (or rower 250m)',
        prescription: '5 rounds (rest 90s)',
        type: 'time',
        durationSec: 60,
        segments: ['Round 1', 'Round 2', 'Round 3', 'Round 4', 'Round 5'],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'gym-lower-focus',
    number: 30,
    name: 'Gym Lower Focus + Upper Maintenance',
    durationMin: 60,
    group: 'full_body',
    intensity: 'deep',
    whenToDo:
      'Use as the second leg-heavy day if running 4-day week. Lower body gets the volume; upper body gets just enough to maintain.',
    whyItWorks:
      'Most intermediate lifters under-train legs and over-train chest. This day fixes that — squats + RDLs + lunges hit every part of the lower body, and upper work is kept minimal so legs actually recover and grow.',
    exercises: [
      {
        name: 'Warmup: bike + leg swings + CARs',
        prescription: '8 min',
        type: 'time',
        durationSec: 480,
      },
      {
        name: 'Back squat',
        prescription: '5 sets × 5',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Romanian deadlift',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Walking lunge (DB or BB)',
        prescription: '3 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Pull-up',
        prescription: '4 sets × 6',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB shoulder press',
        prescription: '3 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hanging leg raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Glute bridge (BB or DB)',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
];
