import type { Routine } from '@/lib/types';

export const routines: Routine[] = [
  {
    id: 'quick-hip-reset',
    number: 1,
    name: 'Quick Hip Reset',
    durationMin: 10,
    group: 'hip_mobility',
    intensity: 'dynamic',
    whenToDo:
      'Daily / anytime. Use as a morning greaser, pre-work, or when you’ve been sitting 3+ hours. No CNS cost — do it daily.',
    whyItWorks:
      'Hits rotation, flexion, abduction in under 10 min. Nothing loaded, nothing held long — pure movement prep.',
    exercises: [
      {
        name: "World's greatest stretch",
        prescription: '5/side, slow',
        type: 'reps',
        reps: 5,
        segments: ['Right', 'Left'],
      },
      {
        name: '90/90 transitions (no hold)',
        prescription: '10 switches',
        type: 'reps',
        reps: 10,
      },
      {
        name: 'Hip circles (CARs) each leg',
        prescription: '5 forward / 5 back',
        type: 'reps',
        reps: 5,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Cossack squats',
        prescription: '10 total',
        type: 'reps',
        reps: 10,
      },
      {
        name: 'Deep squat hold + pulse',
        prescription: '60s',
        type: 'time',
        durationSec: 60,
      },
      {
        name: 'Standing leg swings (front/back + side)',
        prescription: '10 each direction, each leg',
        type: 'reps',
        reps: 10,
        segments: [
          'Right — front/back',
          'Right — side',
          'Left — front/back',
          'Left — side',
        ],
      },
    ],
  },
  {
    id: 'deep-90-90-focus',
    number: 2,
    name: 'Deep 90/90 Focus',
    durationMin: 25,
    group: 'hip_mobility',
    intensity: 'deep',
    whenToDo:
      'Rest day evening. Your weakest test — goes hard on hip rotation and nothing else.',
    whyItWorks:
      'Passive hold + active contract-relax (the lift-offs) is the PNF approach that actually changes ROM. Don’t skip the active reps.',
    exercises: [
      {
        name: 'Warmup: shin box transitions',
        prescription: '2 min (slow switches)',
        type: 'time',
        durationSec: 120,
      },
      {
        name: '90/90 stretch — right lead',
        prescription: '3 min hold',
        type: 'time',
        durationSec: 180,
      },
      {
        name: '90/90 active lift-offs — right',
        prescription: '10 reps (2 sec hold each)',
        type: 'reps',
        reps: 10,
      },
      {
        name: '90/90 stretch — left lead',
        prescription: '3 min hold',
        type: 'time',
        durationSec: 180,
      },
      {
        name: '90/90 active lift-offs — left',
        prescription: '10 reps',
        type: 'reps',
        reps: 10,
      },
      {
        name: 'Seated shin box (both sides)',
        prescription: '3 min flow',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Supine internal rotation (windmill knees)',
        prescription: '2 min each side',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Pigeon pose right',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Pigeon pose left',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: "Child's pose cooldown",
        prescription: '1 min',
        type: 'time',
        durationSec: 60,
      },
    ],
  },
  {
    id: 'external-rotation-deep-dive',
    number: 3,
    name: 'External Rotation Deep Dive',
    durationMin: 30,
    group: 'hip_mobility',
    intensity: 'deep',
    whenToDo:
      'Rest day evening. External rotation = roundhouse kick height + wide stance. Your kick power session.',
    whyItWorks:
      'Every position here forces external rotation under different tensions. The torso rotation over 90/90 is the carryover to actually kicking.',
    exercises: [
      {
        name: 'Cossack squats',
        prescription: '12 total',
        type: 'reps',
        reps: 12,
      },
      {
        name: 'Frog rocks',
        prescription: '15 reps (gentle)',
        type: 'reps',
        reps: 15,
      },
      {
        name: 'Pigeon pose right (active — lift back knee 5x, then relax)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Pigeon pose left (same)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Half pigeon with forward fold (right)',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Half pigeon with forward fold (left)',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: '90/90 with torso rotation over front leg',
        prescription: '2 min each side',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Deep butterfly + slow forward fold',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Seated straddle with reach',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Happy baby',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
    ],
  },
  {
    id: 'internal-rotation-shin-box',
    number: 4,
    name: 'Internal Rotation & Shin Box',
    durationMin: 20,
    group: 'hip_mobility',
    intensity: 'medium',
    whenToDo:
      'The sneaky one — gets ignored, causes low-back compensation. Do this 1x/week minimum.',
    whyItWorks:
      "The shin box is the single best drill for hip rotation you don’t already use. Flow both directions — don’t skip the “weaker” side.",
    exercises: [
      {
        name: 'Windshield wipers (lying, knees bent)',
        prescription: '20 reps',
        type: 'reps',
        reps: 20,
      },
      {
        name: 'Seated shin box flow (both directions)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: '90/90 — front leg internal rotation lift-offs',
        prescription: '10 reps each side',
        type: 'reps',
        reps: 10,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Kneeling with shins rotated out, hips back',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Supine figure-4 + pull to chest',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Standing hip CAR (big slow circles)',
        prescription: '5 each direction, each leg',
        type: 'reps',
        reps: 5,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Deep squat with knees pressed out',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
    ],
  },
  {
    id: 'post-ride-hip-flush',
    number: 5,
    name: 'Post-Ride Hip Flush',
    durationMin: 15,
    group: 'hip_mobility',
    intensity: 'light',
    whenToDo:
      'Saturday night after Ténéré/Beta. Moto riding jacks up hip flexors, glute meds, and low back — this is the specific decompression.',
    whyItWorks:
      'Enduro + adventure riding loads your flexors despite the "pass" test — the riding position shortens them for hours. Couch stretch undoes it. Legs-up-the-wall flushes pooled blood after a long day.',
    exercises: [
      {
        name: "Child's pose with side reach",
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Couch stretch (kneeling, foot on couch/wall)',
        prescription: '2 min each side',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Pigeon pose',
        prescription: '2 min each side',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Supine twist',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Happy baby',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Legs-up-the-wall',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
    ],
  },
  {
    id: 'hamstring-ladder',
    number: 6,
    name: 'Hamstring Ladder',
    durationMin: 25,
    group: 'legs',
    intensity: 'deep',
    whenToDo:
      'Rest day or post-Muay Thai. Your #2 weak point and direct limiter to kick height — hits hamstrings from 4 different angles.',
    whyItWorks:
      'Supine (safest, deepest) + seated (stretches belly of muscle) + standing (functional). PNF at the end is what breaks the plateau.',
    exercises: [
      {
        name: 'Warmup: leg swings front/back',
        prescription: '15 each leg',
        type: 'reps',
        reps: 15,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Standing forward fold (slight bend in knees → straighten)',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Supine single-leg hamstring stretch with strap/belt',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Same position + ankle dorsiflex (loads sciatic nerve — gentle)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Standing hamstring stretch — foot on chair/bench',
        prescription: '2 min each leg',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Seated single-leg forward fold',
        prescription: '2 min each leg',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Seated wide straddle fold',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'PNF finisher: lie on back, strap foot, contract 5s → relax 10s deeper',
        prescription: '3 rounds each leg',
        type: 'reps',
        reps: 3,
        segments: ['Right', 'Left'],
      },
    ],
  },
  {
    id: 'adductor-groin-opener',
    number: 7,
    name: 'Adductor / Groin Opener',
    durationMin: 25,
    group: 'legs',
    intensity: 'deep',
    whenToDo:
      'Your #3 priority. Don’t go crazy — adductors are injury-prone when over-stretched.',
    whyItWorks:
      'Graded frog (light → deeper) is safer than diving into max depth. Cossacks and wide squat hit dynamic range under load.',
    exercises: [
      {
        name: 'Cossack squats',
        prescription: '15 total',
        type: 'reps',
        reps: 15,
      },
      {
        name: 'Side lunge stretch (low)',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Frog pose (light — 60%)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Frog rocks (active)',
        prescription: '15 reps',
        type: 'reps',
        reps: 15,
      },
      {
        name: 'Frog pose (deeper — 75%)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Butterfly with slow fold',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Wide squat hold, elbows pressing knees out',
        prescription: '90s',
        type: 'time',
        durationSec: 90,
      },
      {
        name: 'Seated straddle, reach forward',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Seated straddle, reach each side',
        prescription: '90s each',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Supine figure-4 (opposite of adductor — balance)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
    ],
  },
  {
    id: 'couch-stretch-quad-chain',
    number: 8,
    name: 'Couch Stretch + Quad Chain',
    durationMin: 20,
    group: 'legs',
    intensity: 'medium',
    whenToDo:
      'Post-lift, or day after squats. You pass hip flexors but lifting heavy keeps them tight anyway.',
    whyItWorks:
      'Couch stretch is the king for quads + hip flexors in one. Post-squat it prevents gradual shortening that would eventually fail your hip flexor test.',
    exercises: [
      {
        name: 'Kneeling hip flexor stretch (rear foot down)',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Couch stretch (rear shin vertical on wall/couch)',
        prescription: '2 min each side',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Standing quad pull (grab foot behind, drive knee down)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Side-lying quad stretch',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: "Child's pose with arms extended",
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Supine figure-4',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Cobra / upward dog (opens anterior chain)',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
    ],
  },
  {
    id: 'calves-ankles-feet',
    number: 9,
    name: 'Calves, Ankles & Feet',
    durationMin: 15,
    group: 'legs',
    intensity: 'light',
    whenToDo:
      'Muay Thai footwork, surfing pop-ups, enduro pegs — all ankle/calf dependent. This session gets ignored and it’s a common kick-power leak.',
    whyItWorks:
      'Teep kick power starts at the calf/ankle. Poor dorsiflexion = stunted teep chamber. Soleus work especially — most people only do straight-leg calf stretches.',
    exercises: [
      {
        name: 'Toe spread/stretch (hands interlaced in toes)',
        prescription: '60s each foot',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Downward dog with alternating heel drops',
        prescription: '10 each side',
        type: 'reps',
        reps: 10,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Wall calf stretch — straight knee (gastroc)',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Wall calf stretch — bent knee (soleus)',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Kneeling ankle dorsiflexion (knee past toes)',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Deep squat hold + ankle rocks',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Seated shin stretch (tops of feet)',
        prescription: '60s',
        type: 'time',
        durationSec: 60,
      },
    ],
  },
  {
    id: 'full-lower-body-evening-flow',
    number: 10,
    name: 'Full Lower Body Evening Flow',
    durationMin: 35,
    group: 'legs',
    intensity: 'deep',
    whenToDo:
      'Monday or Wednesday evening. This is your main session — all three weak points hit in one. Do 2–3x/week and actual progress happens.',
    whyItWorks:
      'The engine. Hip rotation + hamstrings + adductors in one deliberate sequence. Never the day before or day of heavy deadlifts/squats.',
    exercises: [
      {
        name: 'Warmup: cossack squats',
        prescription: '10 total',
        type: 'reps',
        reps: 10,
      },
      {
        name: 'Warmup: hip CARs',
        prescription: '5 each way, each leg',
        type: 'reps',
        reps: 5,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Warmup: windshield wipers',
        prescription: '20 reps',
        type: 'reps',
        reps: 20,
      },
      {
        name: '90/90 right — passive then 5 lift-offs',
        prescription: '4 min',
        type: 'time',
        durationSec: 240,
      },
      {
        name: '90/90 left — same',
        prescription: '4 min',
        type: 'time',
        durationSec: 240,
      },
      {
        name: 'Pigeon right (with fold)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Pigeon left (with fold)',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Frog pose',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Seated straddle fold',
        prescription: '3 min',
        type: 'time',
        durationSec: 180,
      },
      {
        name: 'Supine hamstring (strap, each leg)',
        prescription: '2 min each',
        type: 'time',
        durationSec: 120,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Couch stretch each side',
        prescription: '90s each',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Legs-up-the-wall cooldown',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
    ],
  },
  {
    id: 'moto-rider-neck-forearms',
    number: 11,
    name: 'Moto Rider Neck & Forearms',
    durationMin: 12,
    group: 'upper_body',
    intensity: 'light',
    whenToDo:
      'After any ride >1 hour. Specific to Ténéré (long adventure) and Beta (arm pump on tight enduro).',
    whyItWorks:
      'Helmet neck fatigue is neck extensor + upper trap dominance — this decompresses it. Forearm pump recovery comes from stretching the exact muscle groups you burned.',
    exercises: [
      {
        name: 'Neck side bends (ear to shoulder, hand gentle overpull)',
        prescription: '45s each side',
        type: 'time',
        durationSec: 45,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Neck rotations slow',
        prescription: '5 each direction',
        type: 'reps',
        reps: 5,
        segments: ['Clockwise', 'Counter-clockwise'],
      },
      {
        name: 'Chin tucks (against wall)',
        prescription: '10 reps',
        type: 'reps',
        reps: 10,
      },
      {
        name: 'Upper trap stretch (hand behind back + tilt)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Levator scap stretch (look into armpit)',
        prescription: '45s each side',
        type: 'time',
        durationSec: 45,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Forearm flexor stretch (palm up, pull fingers back)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Forearm extensor stretch (palm down, pull fingers down)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Wrist circles',
        prescription: '10 each direction',
        type: 'reps',
        reps: 10,
        segments: ['Clockwise', 'Counter-clockwise'],
      },
      {
        name: 'Thread the needle (shoulder blade opener)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
    ],
  },
  {
    id: 'thoracic-shoulder-opener',
    number: 12,
    name: 'Thoracic & Shoulder Opener',
    durationMin: 15,
    group: 'upper_body',
    intensity: 'medium',
    whenToDo:
      '2x/week, ideally before upper lift or surf. Lets you paddle without grinding low back, press deep with healthy shoulders, clinch cleaner.',
    whyItWorks:
      'T-spine extension is where surfing, overhead pressing, and paddle stroke all live. Foam roller extensions + wall angels actually changes posture over a few weeks.',
    exercises: [
      {
        name: 'Cat-cow',
        prescription: '10 reps',
        type: 'reps',
        reps: 10,
      },
      {
        name: 'Thread the needle',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Quadruped T-spine rotation (hand behind head)',
        prescription: '8 each side',
        type: 'reps',
        reps: 8,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Prayer stretch / puppy pose',
        prescription: '90s',
        type: 'time',
        durationSec: 90,
      },
      {
        name: 'Foam roller T-spine extensions (or rolled towel)',
        prescription: '8 slow extensions',
        type: 'reps',
        reps: 8,
      },
      {
        name: 'Doorway pec stretch (low, mid, high)',
        prescription: '30s each, each side',
        type: 'time',
        durationSec: 30,
        segments: [
          'Right — low',
          'Right — mid',
          'Right — high',
          'Left — low',
          'Left — mid',
          'Left — high',
        ],
      },
      {
        name: 'Behind-back towel stretch (overhead pull-apart)',
        prescription: '90s',
        type: 'time',
        durationSec: 90,
      },
      {
        name: 'Shoulder CARs',
        prescription: '3 each direction, each arm',
        type: 'reps',
        reps: 3,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Wall angels',
        prescription: '10 slow reps',
        type: 'reps',
        reps: 10,
      },
    ],
  },
  {
    id: 'post-lift-upper-flush',
    number: 13,
    name: 'Post-Lift Upper Flush',
    durationMin: 15,
    group: 'upper_body',
    intensity: 'light',
    whenToDo:
      'After a bench/row/press session. Quick decompression, nothing deep. Keep pre-sleep if you lifted evening.',
    whyItWorks:
      'Pec + lat + delt are the 3 muscles you just pumped up and shortened. Hitting all three post-workout keeps shoulder position from drifting forward over years.',
    exercises: [
      {
        name: "Child's pose with side walk (reach right, then left)",
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Doorway pec stretch mid-height',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Cross-body shoulder stretch',
        prescription: '45s each side',
        type: 'time',
        durationSec: 45,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Overhead triceps stretch',
        prescription: '45s each side',
        type: 'time',
        durationSec: 45,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Lat stretch (hold rack/door, hips back)',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Thread the needle',
        prescription: '60s each side',
        type: 'time',
        durationSec: 60,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Supine twist',
        prescription: '90s each side',
        type: 'time',
        durationSec: 90,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Neck side bends',
        prescription: '30s each side',
        type: 'time',
        durationSec: 30,
        segments: ['Right', 'Left'],
      },
    ],
  },
  {
    id: 'morning-full-body-wake-up',
    number: 14,
    name: 'Morning Full Body Wake-Up',
    durationMin: 12,
    group: 'full_body',
    intensity: 'dynamic',
    whenToDo:
      'Daily. Zero CNS cost — do it on the floor next to your bed. No holds over 30s.',
    whyItWorks:
      'Wakes up every joint without any deep stretch. Best use: morning after enduro or heavy leg day, when everything feels crunchy but you need to move.',
    exercises: [
      {
        name: 'Cat-cow',
        prescription: '10 reps',
        type: 'reps',
        reps: 10,
      },
      {
        name: "Child's pose → cobra flow",
        prescription: '8 flows',
        type: 'reps',
        reps: 8,
      },
      {
        name: 'Down dog → plank → up dog flow',
        prescription: '5 flows',
        type: 'reps',
        reps: 5,
      },
      {
        name: "World's greatest stretch",
        prescription: '5 each side',
        type: 'reps',
        reps: 5,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Hip CARs',
        prescription: '5 each way, each leg',
        type: 'reps',
        reps: 5,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Shoulder CARs',
        prescription: '5 each way, each arm',
        type: 'reps',
        reps: 5,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Standing forward fold → roll up',
        prescription: '3 reps slow',
        type: 'reps',
        reps: 3,
      },
      {
        name: 'Deep squat hold',
        prescription: '60s',
        type: 'time',
        durationSec: 60,
      },
      {
        name: 'Standing side bends',
        prescription: '5 each side',
        type: 'reps',
        reps: 5,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Neck rotations',
        prescription: '5 each way',
        type: 'reps',
        reps: 5,
        segments: ['Clockwise', 'Counter-clockwise'],
      },
    ],
  },
  {
    id: 'pre-muay-thai-dynamic-warmup',
    number: 15,
    name: 'Pre-Muay Thai Dynamic Warmup',
    durationMin: 15,
    group: 'full_body',
    intensity: 'dynamic',
    whenToDo:
      'Before Muay Thai class. Dynamic only — no deep static holds, which would reduce power output for kicks.',
    whyItWorks:
      'Hits every joint, raises core temp, primes hip rotators without killing power. Shadow kicks at the end are what bridges warmup to actual Muay Thai.',
    exercises: [
      {
        name: 'Jump rope (or jog in place)',
        prescription: '2 min',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Leg swings front/back',
        prescription: '15 each leg',
        type: 'reps',
        reps: 15,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Leg swings side to side',
        prescription: '15 each leg',
        type: 'reps',
        reps: 15,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Hip circles / CARs',
        prescription: '5 each way, each leg',
        type: 'reps',
        reps: 5,
        segments: ['Right — forward', 'Right — back', 'Left — forward', 'Left — back'],
      },
      {
        name: 'Cossack squats',
        prescription: '12 total',
        type: 'reps',
        reps: 12,
      },
      {
        name: 'Deep squat + reach up, alternating',
        prescription: '10 reps',
        type: 'reps',
        reps: 10,
      },
      {
        name: "Lunge with rotation (world's greatest)",
        prescription: '5 each side',
        type: 'reps',
        reps: 5,
        segments: ['Right', 'Left'],
      },
      {
        name: 'Knee drive + opposite elbow',
        prescription: '20 total',
        type: 'reps',
        reps: 20,
      },
      {
        name: 'Inchworm to plank, shoulder tap, walk back',
        prescription: '5 reps',
        type: 'reps',
        reps: 5,
      },
      {
        name: 'A-skips / high knees',
        prescription: '30s',
        type: 'time',
        durationSec: 30,
      },
      {
        name: 'Light shadow kicks (front, round, side — all low/mid)',
        prescription: '10 each leg',
        type: 'reps',
        reps: 10,
        segments: ['Right', 'Left'],
      },
    ],
  },
];

export const routineGroupLabels: Record<Routine['group'], string> = {
  hip_mobility: 'Hip Mobility',
  legs: 'Legs / Lower Body',
  upper_body: 'Upper Body',
  full_body: 'Full Body',
  kb_only: 'KB Only',
  kb_bodyweight: 'KB + Bodyweight',
  gym: 'Gym',
  lower_body: 'Lower Body',
};

export const intensityLabels: Record<Routine['intensity'], string> = {
  light: 'Light',
  medium: 'Medium',
  deep: 'Deep',
  dynamic: 'Dynamic',
};

export const intensityBadgeClass: Record<Routine['intensity'], string> = {
  deep: 'bg-destructive/10 text-destructive',
  medium: 'bg-primary/10 text-primary',
  light: 'bg-muted text-muted-foreground',
  dynamic: 'bg-secondary text-secondary-foreground',
};
