import type { Routine } from '@/lib/types';

export const yaelRoutines: Routine[] = [
  // ─────────────────────────────────────────────
  // LOWER BODY — GLUTE FOCUS (1–5)
  // ─────────────────────────────────────────────
  {
    id: 'yael-lower-hip-thrust-strength',
    number: 1,
    name: 'Heavy Hip Thrust + Glute Strength',
    durationMin: 60,
    group: 'lower_body',
    intensity: 'deep',
    whenToDo:
      'The glute strength anchor of the week. 1x/week, with at least 48h before next lower day. Add weight when all sets feel clean.',
    whyItWorks:
      'Heavy hip thrust is the single highest-output lift for glute development — more direct than squats, more loadable than kickbacks. Pair it with Bulgarians and RDLs and you cover every angle the glutes work through.',
    exercises: [
      {
        name: 'Warmup: bike or stairmaster',
        prescription: '5 min easy',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'Glute activation: banded clamshell + glute bridge',
        prescription: '2 min flow',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Barbell hip thrust',
        prescription: '5 sets × 6–8 (rest 2 min)',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Bulgarian split squat (DB)',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Romanian deadlift',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Cable glute kickback',
        prescription: '4 sets × 12/side',
        type: 'reps',
        reps: 12,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Hip abductor machine',
        prescription: '4 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-lower-squat-lunge-volume',
    number: 2,
    name: 'Squat & Lunge Volume',
    durationMin: 60,
    group: 'lower_body',
    intensity: 'medium',
    whenToDo:
      'The hypertrophy lower day. Slot mid-week between heavy hip thrust and posterior chain. Moderate weight, controlled tempo.',
    whyItWorks:
      'Squats + lunges + step-ups hit glutes through full hip flexion under load — the angle hip thrusts miss. Higher reps with shorter rest = the muscle-building sweet spot for legs.',
    exercises: [
      {
        name: 'Warmup: bike + leg swings',
        prescription: '6 min',
        type: 'time',
        durationSec: 360,
      },
      {
        name: 'Glute activation: monster walk',
        prescription: '2 sets × 15 steps each direction',
        type: 'reps',
        reps: 15,
        segments: ['Set 1 — Forward', 'Set 1 — Back', 'Set 2 — Forward', 'Set 2 — Back'],
      },
      {
        name: 'Goblet squat (deep, paused)',
        prescription: '4 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB walking lunge',
        prescription: '4 sets × 12/side',
        type: 'reps',
        reps: 12,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'High step-up (DB)',
        prescription: '3 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Sumo deadlift',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Barbell glute bridge',
        prescription: '3 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hanging knee raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-lower-posterior-chain',
    number: 3,
    name: 'Posterior Chain & Hamstring',
    durationMin: 55,
    group: 'lower_body',
    intensity: 'deep',
    whenToDo:
      'The hamstring/posterior day. Use as your second heavy lower session, with at least 48h from hip thrust day. Sumo deadlift is the centerpiece.',
    whyItWorks:
      'Sumo deadlift hits glutes harder than conventional thanks to the wider stance and more upright torso. Pairing it with single-leg RDLs and curls covers every fiber from glute insertion down to knee.',
    exercises: [
      {
        name: 'Warmup: bike + bird dog + cat-cow',
        prescription: '6 min',
        type: 'time',
        durationSec: 360,
      },
      {
        name: 'Sumo deadlift',
        prescription: '5 sets × 5 (rest 2 min)',
        type: 'reps',
        reps: 5,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      },
      {
        name: 'Hip thrust (moderate)',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Single-leg RDL (DB)',
        prescription: '3 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Lying hamstring curl machine',
        prescription: '4 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Cable pull-through',
        prescription: '3 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Russian twist (plate)',
        prescription: '3 sets × 20',
        type: 'reps',
        reps: 20,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-lower-glute-pump',
    number: 4,
    name: 'Glute Hypertrophy Pump',
    durationMin: 50,
    group: 'lower_body',
    intensity: 'medium',
    whenToDo:
      'The "feel-it" day — high-volume, machine + cable focus, less CNS cost. Use between heavy lower days or as your fourth lower session if running 4 leg days.',
    whyItWorks:
      'High-rep cable + machine work nails the glute pump where heavy barbells leave reps on the table. The drop set at the end pushes past failure on muscles that respond well to metabolic stress.',
    exercises: [
      {
        name: 'Warmup: bike + glute bridges',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'Glute activation: monster walk + clamshells',
        prescription: '2 min flow',
        type: 'time',
        durationSec: 120,
      },
      {
        name: 'Smith machine sumo squat',
        prescription: '4 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Standing cable kickback',
        prescription: '4 sets × 15/side',
        type: 'reps',
        reps: 15,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Cable hip abduction (standing)',
        prescription: '4 sets × 15/side',
        type: 'reps',
        reps: 15,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'DB reverse lunge',
        prescription: '3 sets × 12/side',
        type: 'reps',
        reps: 12,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Frog pump',
        prescription: '3 sets × 20',
        type: 'reps',
        reps: 20,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hip abductor machine — drop set',
        prescription: '3 sets × 20→15→10 (drop weight each)',
        type: 'reps',
        reps: 20,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-lower-glute-power-plyo',
    number: 5,
    name: 'Glute Power & Plyometric',
    durationMin: 45,
    group: 'lower_body',
    intensity: 'deep',
    whenToDo:
      'The athletic day — once a week max. Needs fresh legs. Pairs explosive jumps with heavy hip thrusts (contrast training). Skip if you slept badly.',
    whyItWorks:
      'Contrast training (heavy strength + explosive plyo back-to-back) recruits more motor units than either does alone. Builds shape AND athleticism — the muscle gets denser, not just bigger.',
    exercises: [
      {
        name: 'Warmup: dynamic — leg swings, A-skips, jump rope',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'Box jump',
        prescription: '4 sets × 6 (rest 90s)',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Heavy hip thrust (contrast)',
        prescription: '4 sets × 6',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Bulgarian split squat (DB)',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'KB swing',
        prescription: '4 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB walking lunge',
        prescription: '3 sets × 20 steps',
        type: 'reps',
        reps: 20,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hollow hold',
        prescription: '3 sets × 30s',
        type: 'time',
        durationSec: 30,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // UPPER BODY — PURE UPPER + CORE FINISHER (6–10)
  // ─────────────────────────────────────────────
  {
    id: 'yael-upper-shoulders-chest',
    number: 6,
    name: 'Shoulders & Chest Sculpt',
    durationMin: 55,
    group: 'upper_body',
    intensity: 'medium',
    whenToDo:
      'The push-focus day. Slot opposite a pull day, with at least 48h between two push sessions. Lateral raises are the priority — they build the "shoulder cap" look.',
    whyItWorks:
      'Lateral and rear delts are the visual difference between flat shoulders and the rounded look. Most women under-train them. Adding moderate chest work keeps the upper body proportional without bulking the pecs.',
    exercises: [
      {
        name: 'Warmup: bike + arm circles + band pull-aparts',
        prescription: '6 min',
        type: 'time',
        durationSec: 360,
      },
      {
        name: 'Seated DB shoulder press',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Incline DB press',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB lateral raise',
        prescription: '4 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Cable chest fly',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Front raise (light DB)',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Triceps rope pushdown',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hanging leg raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-upper-back-biceps',
    number: 7,
    name: 'Back & Biceps Pull Day',
    durationMin: 55,
    group: 'upper_body',
    intensity: 'medium',
    whenToDo:
      'The pull-focus day. Pair with the push day across the week. Strong back = better posture and the "snatched waist" illusion most women are after.',
    whyItWorks:
      'Wide-grip pulls build the lats (visual taper from waist to shoulder). Rows build mid-back thickness for posture. Face pulls fix rounded shoulders from desk work — the silent killer of upper-body aesthetics.',
    exercises: [
      {
        name: 'Warmup: bike + scap pull-ups + band pull-aparts',
        prescription: '6 min',
        type: 'time',
        durationSec: 360,
      },
      {
        name: 'Lat pulldown (wide grip)',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Seated cable row',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Single-arm DB row',
        prescription: '4 sets × 10/side',
        type: 'reps',
        reps: 10,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
          'Set 4 — Right',
          'Set 4 — Left',
        ],
      },
      {
        name: 'Face pull',
        prescription: '4 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB bicep curl',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hammer curl',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Cable woodchopper',
        prescription: '3 sets × 12/side',
        type: 'reps',
        reps: 12,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Side plank',
        prescription: '3 sets × 30s/side',
        type: 'time',
        durationSec: 30,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
    ],
  },
  {
    id: 'yael-upper-sculpt-volume',
    number: 8,
    name: 'Shoulders & Arms Sculpt',
    durationMin: 50,
    group: 'upper_body',
    intensity: 'medium',
    whenToDo:
      'The accessory/sculpt day — high reps, cables, drop sets. Slot between heavy push and pull days. Lower CNS cost so it fits anywhere in the week.',
    whyItWorks:
      'Cable + isolation work at high reps maximizes time-under-tension on the small muscles (medial delts, biceps, triceps) that finish the upper-body shape. Drop sets push these muscles past where straight sets can.',
    exercises: [
      {
        name: 'Warmup: bike + dynamic shoulder',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'DB lateral raise — drop set',
        prescription: '4 sets × 12→10→8 (drop each)',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Seated DB shoulder press',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Cable rope face pull',
        prescription: '4 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Single-arm cable lateral raise',
        prescription: '3 sets × 12/side',
        type: 'reps',
        reps: 12,
        segments: [
          'Set 1 — Right',
          'Set 1 — Left',
          'Set 2 — Right',
          'Set 2 — Left',
          'Set 3 — Right',
          'Set 3 — Left',
        ],
      },
      {
        name: 'Reverse pec-deck (rear delt fly)',
        prescription: '3 sets × 15',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Cable rope tricep extension',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Cable bicep curl',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Russian twist (plate)',
        prescription: '3 sets × 20',
        type: 'reps',
        reps: 20,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-upper-superset-volume',
    number: 9,
    name: 'Push/Pull Superset Volume',
    durationMin: 60,
    group: 'upper_body',
    intensity: 'medium',
    whenToDo:
      'The density day — supersets keep heart rate up while still building muscle. Good fat-loss day since it doubles as conditioning. Use later in the week.',
    whyItWorks:
      'Antagonist supersets (push paired with pull) cut total workout time without dropping volume — and the elevated heart rate burns more calories than straight sets. Best of both worlds for muscle gain + fat loss.',
    exercises: [
      {
        name: 'Warmup: bike + dynamic shoulder',
        prescription: '5 min',
        type: 'time',
        durationSec: 300,
      },
      {
        name: 'A1: Lat pulldown',
        prescription: '4 sets × 10 (superset with A2)',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'A2: DB shoulder press',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'B1: Seated cable row',
        prescription: '4 sets × 10 (superset with B2)',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'B2: Incline DB press',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'C1: Face pull',
        prescription: '3 sets × 15 (superset with C2)',
        type: 'reps',
        reps: 15,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'C2: DB lateral raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'D1: DB bicep curl',
        prescription: '3 sets × 12 (superset with D2)',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'D2: Triceps pushdown',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hanging knee raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
  {
    id: 'yael-upper-strength-circuit',
    number: 10,
    name: 'Upper Strength Circuit',
    durationMin: 50,
    group: 'upper_body',
    intensity: 'deep',
    whenToDo:
      'The lower-rep strength day. Once a week. Real strength work in the 6–8 rep range — push slightly heavier than the volume days.',
    whyItWorks:
      'Most "girl-coded" upper programs live at 12+ reps and never get strong. A weekly heavier session (6–8 reps) is what keeps muscle from plateauing — and progressively heavier weights are the actual driver of body composition change, not just rep count.',
    exercises: [
      {
        name: 'Warmup: bike + dynamic + band pull-aparts',
        prescription: '6 min',
        type: 'time',
        durationSec: 360,
      },
      {
        name: 'Pull-up (assisted machine if needed)',
        prescription: '4 sets × 6',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB bench press',
        prescription: '4 sets × 8',
        type: 'reps',
        reps: 8,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Standing overhead press (DB or BB)',
        prescription: '4 sets × 6',
        type: 'reps',
        reps: 6,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'Bent-over DB row',
        prescription: '4 sets × 10',
        type: 'reps',
        reps: 10,
        segments: ['Set 1', 'Set 2', 'Set 3', 'Set 4'],
      },
      {
        name: 'DB lateral raise',
        prescription: '3 sets × 12',
        type: 'reps',
        reps: 12,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Plank',
        prescription: '3 sets × 45s',
        type: 'time',
        durationSec: 45,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Mountain climbers',
        prescription: '3 sets × 30s',
        type: 'time',
        durationSec: 30,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
      {
        name: 'Hollow hold',
        prescription: '3 sets × 30s',
        type: 'time',
        durationSec: 30,
        segments: ['Set 1', 'Set 2', 'Set 3'],
      },
    ],
  },
];
